### ISSUE TITLE
Path meta issue

### ISSUE THREAD

**Issue by marron-at-work** [BosqueLanguage/BREX#9]
Path support is limited in the library. Some of this will need to be resolved for Bosque 1.0 but we don't really need paths to implement the 1.0 compiler so others can be delayed a bit.

- [ ] Representations -- we need to have the Path (done), Fragment (pending), and Glob (done) representations + the json parsing for them done.
- [ ] Literal Parser -- we need to have a parser for the literal values.
- [ ] Glob inclusion -- if a Glob g1 if of structure g2 then in theory the regular language recognized by g1 should be included in g2. However this is a PSpace problem :( so we are going to do a simple set of heuristic checks for non-emptiness of the languages -- e.g. if they have a literal path component that is not in common.
- [ ] Path Glob matching -- need a custom regex-style matcher -- should check the Glob and Glob type chain (since we don't statically ensure language inclusion).

Notes on glob semantics:
    //
    //  /x/y/*     <-- all files in y
    //  /x/y/*/    <-- all directories in y
    //  /x/y/+     <-- all files *and* directories in y
    //
    //  /x/y/**   <-- all files (recursively) reachable from y
    //  /x/y/**/  <-- all directories (recursively) reachable from y
    //  /x/y/++  <-- all files *and* directories (recursively) reachable from in y
    //
    //  /x/y/*.*     <-- all files in y with an extension
    //  /x/y/**/*.*  <-- all files (recursively) reachable from y with an extension
    //
